# -*- coding: utf-8 -*-
"""Error Handling: Raise an exception Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIyZb1pHAjPO05oQDenFpAAbETfsquH2
"""

# 1.
# Basic use of raise

num = int(input('Enter Number '))
if num%2 != 0:
  raise Exception('Number is not Even')

# 2.
# Raise Specific Exception Type

try:
  b= int('python')
except ValueError:
  raise ValueError('String can not be convert into integer')

# 3.
# Re-raising an Exception

try:
    num = int('orange')
except:
    raise

# 4.
# Raising error in function

def age(a):
  if a<0:
    raise ValueError ('Age cannot be negetive')
  print(f'Your age = {a} years')

ag= int(input('Enter Your age'))

try:
  print(age(ag))
except ValueError as e:
  print(e)

