# -*- coding: utf-8 -*-
"""File Handling 4: json module Part 1: Converting json to python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGzyFYrssY1l_2UeXO4p67L3C83lrTqY

This include:

1.   JSON data loading, using json.load (Returns a Python object representing the JSON data.)
2.   Nested JSON structures
3. Performing data aggregation
4. Use of json.loads()
5. Python JSON to Ordered Dictionary

# Using json.load()
"""

import json

with open('economic_indicators.json','r') as jsonf:
  j_data= json.load(jsonf)
  print(j_data)

print('\n', j_data['Data_id'],'\n', j_data['Date'],'\n', j_data['Data'])
print(j_data['info']['Total_indicator'])

total_val = sum(hd['value'] for indicator in j_data['Data'] for hd in indicator['historical_data'])
print(f"Total sum of all historical values: {total_val}")

"""# Using josn.loads()"""

import json

json_string = '{"language": "Python", "version": 3.11}'
json_array = '["Python","Java","C++"]'

j_data1 = json.loads(json_string) #convert to python dictionary
j_data2 = json.loads(json_array)  #convert to python list

print(j_data1)
print(j_data2)
print('\nProgramming language = ',j_data1['language'])

# Python JSON to Ordered Dictionary
# object_pairs_hook=OrderedDict

from collections import OrderedDict

json_string= '{"Indian":1, "National":2, "State":3}'
j_data= json.loads(json_string, object_pairs_hook= OrderedDict)
print(j_data)