# -*- coding: utf-8 -*-
"""File Handling 3: CSV I/O using Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nZCRa73tXisa_aJoGDPD3QAWv2EQ88s
"""

with open('dummy_csvfile.txt','a') as f:
  data= f.write('\n11,Jhon,N/A,Houston,N/A')
  data= f.write('\n12,N/A,25,Seattle,90')

import pandas as pd

data= pd.read_csv('dummy_csvfile.txt', nrows=5, skiprows=[2,4,5,6,8,10])
data

# 1. Read specific columns using read_csv
data= pd.read_csv('dummy_csvfile.txt', usecols=['Name','Score'], nrows=5)       # Can use indexing also in 'usecols'
data

# 2. Setting an Index Column (index_col)

data= pd.read_csv('dummy_csvfile.txt', index_col='City', nrows=5)         # can also use indexing
data

# 3. Handling Missing Values Using read_csv

data= pd.read_csv('dummy_csvfile.txt', nrows=3, na_values=['N/A','Alice'])        # Tells Pandas to treat the strings "N/A" and "Alice" as missing values (NaN)
data

# 4. Reading CSV Files with Different Delimiters
import pandas as pd

data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open("sample.txt", "w") as file:
    file.write(data)

csv_file= pd.read_csv('sample.txt', sep='[,.:|_]',engine='python' )
csv_file
