# -*- coding: utf-8 -*-
"""File Handling 5: JSON module Part 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16m0fWQxUafzzBM7ffXh2MXJa8m9k_zs3

This file include:


1.   Writing a Python dictionary into a JSON file using json.dump().
2.   Avoids errors when keys are not JSON-compatible
3.   Preserving non-ASCII characters
4.   Sorts dictionary keys alphabetically before converting them to JSON
5.   JSON to String using an API using requests
6.   Formatting JSON

# Using json.dump()
"""

# 1. writing a Python dictionary into a JSON file using json.dump()

import json

data={'Name':'Rohan Sharma','Age':24,'Department':'HR'}
with open('dummy.json','w') as jsonfile:
  json.dump(data, jsonfile, indent=4)

# 2. Avoids errors when keys are not JSON-compatible

d = {("x", "y"): 10, "z": 20}
with open("data.json", "w") as f:
    json.dump(d, f, skipkeys= True)

# 3. Preserving non-ASCII characters

d = {"msg": "¡Hola Mundo!"}
with open("text.json", "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=True)

"""# Using json.dumps()"""

import json

d = {"a": "Hello", "b": "World","d":"python","version":3.14}
jd= json.dumps(d, indent=4)
print(jd)
print(type(jd))

# Sorts dictionary keys alphabetically before converting them to JSON

d = {"a": "Hello","version":3.14,"d":"python", "b": "World"}

jd= json.dumps(d, indent=4, sort_keys= True)
print(jd)

# Convert python list to JSON array

a=[1947, 'India','Independent']
json_data= json.dumps(a)
print(json_data)

# Json to String using an API using requests and "json.dumps"

import json
import requests

# Get dummy data using an API
res = requests.get("http://dummy.restapiexample.com/api/v1/employees")

# Convert data to dict
d = json.loads(res.text)

# Convert dict to string
d = json.dumps(d)

print(d)
print(type(d))

"""**Formating JSON**


"""

import json

json_data = '[ {"studentid": 1, "name": "Nikhil", "subjects": ["Python", "Data Structures"]},\
{"studentid": 2, "name": "Nisha", "subjects": ["Java", "C++", "R Lang"]} ]'

data= json.loads(json_data)

json_formatted_string= json.dumps(data, indent=4)
print(json_formatted_string)

"""**Sorting JSON**"""

import json

json_data = '[ {"studentid": 1, "name": "Nikhil", "subjects":\
["Python", "Data Structures"], "company":"abc"},\
{"studentid": 2, "name": "Nisha", "subjects":\
["Java", "C++", "R Lang"], "company":"bca"} ]'

data= json.loads(json_data)

json_sorted_string= json.dumps(data, indent=4, sort_keys= True)
print(json_sorted_string)