# -*- coding: utf-8 -*-
"""File Handling 2: CSV I/O in python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHsK_s6i8mHm36mep6MvJb9cIroFp0-K

# Reading CSV File

Reading a CSV file
"""

import csv

filename= 'dummy_csvfile.txt'
fields=[]         #Columns
rows=[]

with open(filename, 'r') as csvfile:
  csv_data= csv.reader(csvfile)

  fields = next(csv_data)         # returns the next row from the CSV reader.It's usually called immediately after creating the reader, it retrieves the header row.
  for row in csv_data:
    rows.append(row)

# a) Total Number of rows ---------------
print('Number of rows=', csv_data.line_num)

# b) Fields (or columns) ----------------
print('\nField names are:',','.join(fields))

# c) Top 5 rows
print('\nFirst 5 rows')
for row in rows[:5]:
  for col in row:
    print("%10s" % col, end='')         #'%10s'= gap of 10 characters in string format, % col= place col value in between those gaps, end='' =join col values with 1 gap
  print('\n')

"""Reading CSV Files Into a Dictionary With csv

"""

import csv

with open('dummy_csvfile.txt','r') as csvfile:
  csv_data= csv.DictReader(csvfile)

  data_list=[]
  for row in csv_data:
    data_list.append(row)

for data in data_list[:5]:
  print(data)

"""# Writing CSV File"""

import csv

fields= ["Country", "GDP (Billion USD)", "Inflation (%)", "Unemployment (%)", "Population (Million)"]
rows = [
    ["India", 4100, 5.2, 7.1, 1440],
    ["United States", 30500, 2.8, 4.1, 342],
    ["China", 19800, 1.9, 5.3, 1410],
    ["Japan", 4400, 2.3, 2.6, 123],
    ["Germany", 5200, 2.5, 3.4, 84],
    ["United Kingdom", 3900, 3.1, 4.5, 69],
    ["France", 3600, 2.7, 7.2, 66],
    ["Brazil", 2300, 4.4, 8.3, 216],
    ["Canada", 2500, 2.2, 5.8, 41],
    ["Australia", 1900, 2.6, 4.0, 27]
]

with open('economy.csv','w') as csvfile:
  csvdata= csv.writer(csvfile)
  csvdata.writerow(fields)          #writerow
  csvdata.writerows(rows)           #writerow(s)

"""Writing a dictionary to a CSV file

"""

import csv

books = [
{"Book ID": 101, "Title": "Atomic Habits", "Author": "James Clear", "Genre": "Self-help", "Price": 499},
{"Book ID": 102, "Title": "Deep Work", "Author": "Cal Newport", "Genre": "Productivity", "Price": 450},
{"Book ID": 103, "Title": "The Psychology of Money", "Author": "Morgan Housel", "Genre": "Finance", "Price": 399},
{"Book ID": 104, "Title": "Clean Code", "Author": "Robert C. Martin", "Genre": "Programming", "Price": 799},
{"Book ID": 105, "Title": "The Pragmatic Programmer", "Author": "Andrew Hunt", "Genre": "Programming", "Price": 699}
]

fields= ['Book ID','Title','Author','Genre','Price']

with open('Book_data.csv','w') as csvf:
  csv_data= csv.DictWriter(csvf, fieldnames= fields)
  csv_data.writeheader()          # writerow not work here
  csv_data.writerows(books)