# -*- coding: utf-8 -*-
"""Error Handling: Python Built in Exceptions Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVgYdqcNq-HodNR9Uakfk5BYgOoRK7j7
"""

# ZeroDivisionError and ValueError

a= int(input('Numerator='))

try:
  b= int(input('Denominator='))
  c= a/b
  print(c)

except ValueError:
  print('Enter a valid number')

except ZeroDivisionError as e:          # e is the exception object (instance) that contains details about the error.
    print('Please enter a number greater than zero')
    print("Detail of error:" ,e)

else:
  print(c)

finally:
  print('Excecution Completed')

# ArithmeticError and Exception

import math

a=10
b=0
try:
  a/b
except ArithmeticError as e:
  print(e)
try:
  c= math.exp(1000)
except Exception as e:
  print(e)

# Overflow Error

import math
try:
  a= math.exp(1000)   #e^1000
  print(a)
except OverflowError as e:
  print(e)

# AssertionError

try:
  assert 1==2, "<error message= Assertion Failed>"
except AssertionError as e:
  print(e)

# AttributeError

class myclass:
  pass_marks= 30
  total_marks= 100

obj = myclass()

try:
  b= obj.average_marks
  print(b)
except AttributeError as e:
  print(e)

# IndexError

a_list= [12,546, 'hello_world']

try:
  print(a_list[6])
except IndexError as e:
  print(e)

# TypeError

try:
  a= 'dd'+'gg'+ 22
  print(a)
except TypeError as e:
  print(e)