# -*- coding: utf-8 -*-
"""File handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbzO-BqBJFVayC-XpwcKcb700aRJ4g6U

Basic Codes
"""

f= open('sample_file.txt','r')
print(f)          #returns a file object connected to that file
print("File name=", f.name)
print('File mode=', f.mode)
print('Is file closed=', f.closed)

f.close()
print('\nIs file closed=', f.closed)

"""# 1. Reading to File

Reading of Binary files
"""

# Reading file Method - 1 ------
f= open('sample_file.txt', 'r')
data= f.read()
print(data)

f.close()

# Reading file Method - 2 (using with statement)------
# In this method explicitly closing file is not required
with open('sample_file.txt','r') as f:
  data= f.read()
  print('_'*50,'\n',data)

# Reading Binary file (using rb = Output binary)

bin_file= open("binary_data_sample.txt","rb")
data= bin_file.read()
print(data)

# Reading Binary file (using r only = Output string)

bin_file= open("binary_data_sample.txt","r")
data= bin_file.read()
print(data)

# Reading Binary file using readlines()

with open('binary_data_sample.txt','rb') as f:
  lines= f.readlines()
  for i in lines:
    print(i)

# Observe how readline() and readlines() works!

f= open('sample_file_io.txt','r')
line= f.readline()
print(line)
line2= f.readline()
print(line2)
line3= f.readline()
print(line3)

line_s= f.readlines()
print(line_s)

# Reading specific part of file or previewing

f= open('sample_file_io.txt','r')
preview= f.read(31)               #first 31 characters
print(preview)

f.close()

# Reading Binary File in Chunks

size= 50
with open('binary_data_sample.txt','rb') as f:
  while True:
    chunk= f.read(size)
    if not chunk:
      break
    print(chunk)

# Creating in memory csv file
# Reading CSV file

import csv
import io

data= '''name,age,marks
a,12,23
b,13,24'''          #avoid gaps in between

csv_file= io.StringIO(data)
csv_read= csv.reader(csv_file)
for row in csv_read:
  print(row)

"""Reading of JSON files"""

# Reading prebuilded file

import json

with open('dummy.json','r') as file:
  data= json.load(file)

print(json.dumps(data, indent=4))

# Reading json string

import json

json_string= '''{
  "id": 1001,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "age": 28,
  "isActive": true,
  "address": {
    "street": "123 Main Street",
    "city": "New York",
    "country": "USA"
  },
  "skills": [
    "JavaScript",
    "Python",
    "SQL"
  ],
  "createdAt": "2026-06-24T10:00:00Z"
}'''

data= json.loads(json_string)         #used loads()
print(json.dumps(data, indent=5))

# Error handling ------

# FileNotFoundError -----
import json

try:
  with open('durmmy.json','r') as file:
    data= json.load(file)
  print(json.dumps(data, indent=4))

except FileNotFoundError:
  print('FileNotFoundError 1234')

# JSONDecodeError -------
import json

json_string=json_string= '''{
  "id": 1001,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "age": 28,
  "isActive": true,
  "address": {
    "street": "123 Main Street",
    "city": "New York",
    "country": "USA"
  },
  "skills": [
    "JavaScript",
    "Python",
    "SQL"
  ],
  "createdAt": "2026-06-24T10:00:00Z"
'''         # missing '}' at end

try:
  data= json.loads(json_string)
  print(json.dumps(data, indent=4))

except json.JSONDecodeError:
  print('Json decode error 1234')

"""# 2. Writing to File"""

# 1. Overwriting file ---------

with open('dummy_write.txt','w', encoding= 'utf-8') as f:
  f.write('Hello,\n')
  f.write('Python Practice.\n')
  f.write('==It is initial content\n')

with open('dummy_write.txt', 'r') as f:
  data= f.read()
  print(data)


with open('dummy_write.txt','w+', encoding='utf-8') as f:
  f.write('wow!\n')
  f.write('Content of Previous file is erased, and new content is inserted\n')
  f.write('It means file is overwrighted\n')


with open('dummy_write.txt','r') as f:
  data= f.read()
  print(data)

# 2. Appending a file -------

with open('dummy_write.txt', 'a', encoding='utf-8') as f:
  f.write('\nIf you see this:)\n')
  f.write('Then I have appended something to your original file')

with open('dummy_write.txt', 'r') as f:
  data= f.read()
  print(data)

# 3. Create only if file does not exist --------

try:
  with open('dummy_write.txt','x', encoding='utf-8') as f:
    f.write('Hello')

except FileExistsError:
  print(' File with this name already existed')

# 4. Writing multiple lines ----------

line_list= ['\n\nadding multiple line 1\n','adding multiple line 2\n','adding multiple line 3\n']

with open('dummy_write.txt','a', encoding='utf-8') as f:
  f.writelines(line_list)

with open('dummy_write.txt','r') as f:
  data= f.read()
  print(data)

# Another way

line_list=['Line 4','Line 5','Line 6']
line_list_2= '\n'.join(line_list) + '\n'          # make code more efficient

with open('dummy_write.txt', 'a', encoding= 'utf-8') as f:
  f.writelines(line_list_2)

with open('dummy_write.txt', 'r', encoding= 'utf-8') as f:
  data= f.read()
  print(data)

"""Writing in Binary File"""

b= b'\x00,\x05\x06,\x12'

with open('binary_file.bin','wb') as f:
  f.write(b)

with open('binary_file.bin', 'rb') as f:
  data= f.read()
  print(data)

# 6. Writing using Pathlib library

from pathlib import Path

Path('pathlib_write_file.txt').write_text('hello\nHow are you')

data= Path('pathlib_write_file.txt').read_text()
print(data)

# 7. Using method like 'w+'

with open('dummy_write2.txt', 'w+') as f:
    f.write('Hello,\n')
    f.write('Python Practice.\n')

    f.seek(0)
    print(f.read())