# -*- coding: utf-8 -*-
"""Functions_&_scope_PI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWa3yX5V4nKYbrjj23UI7gVh1leFTNAq

1. Function that takes a list and returns the sum of even numbers only.
"""

list_even=[]
def even_number(list):
  i=0
  while (i<len(list)):
    a= list[i]
    if (a%2==0):
      list_even.append(a)
    i=i+1
  return list_even

list=[1,5,2,7,4,9,1]
print(even_number(list))

"""2. Return both: mean &
max
from a list
"""

def mean_max(list):
  a=0
  for i in range(len(list)):
    a +=list[i]
  mean=a/len(list)
  print('Mean= ',mean)

  max=list[0]
  for i in range(len(list)):
    if(i+1!=len(list)):
      if (list[i]<list[i+1]):
        max=list[i+1]
      else:
        max=list[i]
  print('Max=',max)

list=[1,4,3,6,9]
print(mean_max(list))

"""3. Counter that increase count when function is called"""

def counter():
  global count
  count+=1
  return count


print(counter())
print(counter())
print(counter())

"""4. Shadowing problem


*   Why original list not changed?


> Because it is creating a new list in local scope instead of updating given list.


> In corrected version we have modified every element of list 'data'.






"""

# List not modified error

data = [1,2,3]
def process(data):
  data = [x*2 for x in data]
  return data

process(data)
print('shadowing problem= ',data)

# Corrected version

def process_2(data):
  for i in range(len(data)):
    data[i]= data[i]*2
  return data

process_2(data)
print('List is modified= ',data)

"""5. Mutable default argument bug
```
def add_item(item, lst=[]):
    lst.append(item)
    return lst
```
* Call it multiple times → observe bug
* Fix it properly
"""

#Given Version

def add_item(item, lst=[]):
    lst.append(item)
    return lst
add_item(1)
add_item(2)
add_item(3)
print(add_item(4))
print("If a function run multiple times then it will append all the values in one list")

# Corrected version

def add_item(item, lst=None):
  if lst is None:
    lst=[]
  lst.append(item)
  return lst

add_item(1)
add_item(2)
add_item(3)
print("With corrected version=", add_item(4))

"""6. Function inside function (closure intro)
```
def outer(x):
    def inner():
        return x * 2
    return inner()
```


* Modify so inner is returned (not executed)
* Then call it later
"""

# Modification
def outer(x):
    def inner():
        return x * 2
    return inner

# Calling
f= outer(5)
print('output=', f())

